name: Windows
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: PrePack
        run: |
          copy-item -r ./.electron ./electron
          copy-item -r ./css ./electron
          copy-item -r ./js ./electron
          copy-item -r ./layui ./electron
          copy-item ./index.html ./electron
          copy-item ./favicon.ico ./electron/icon.ico
          copy-item ./LICENSE ./electron
          cd electron
          npm i
          (get-content -encoding utf8 ./js/init.js).replace('giftdouyucdn.starudream.cn', 'gift.douyucdn.cn') | set-content -encoding utf8 ./js/init.js
          (get-content -encoding utf8 ./package.json).replace('1.0.0', $env:GITHUB_REF.SubString(11)) | set-content -encoding utf8 ./package.json
      - name: Pack
        run: npm run pack --prefix ./electron
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: electron
          path: ./electron/build
